### ISSUE TITLE
Problems Updating

### ISSUE THREAD

**Issue by jaredcommonmedia** [petterheterjag/chromatic-sketch#3]
Not sure if its a problem with Runner or what, but this plugin constantly says it needs an update and updating (either within Runner or by downloading the latest) doesn't make the alert go away. Just an FYI.

**Comment by petterheterjag** [comment]
@jaredcommonmedia: Hmm, that's weird. I'll try to investigate. If you can post a screenshot of the alert, that might help. Thanks!

**Comment by jaredcommonmedia** [comment]
https://cl.ly/1d2X0S0L3v2q/Screen%20Recording%202017-06-19%20at%2009.29%20AM.gif
