### ISSUE TITLE
Consider implementing LCH

### ISSUE THREAD

**Issue by jlarmstrongiv** [petterheterjag/chromatic-sketch#4]
![image](https://user-images.githubusercontent.com/20903247/30519029-abc72d6c-9b5a-11e7-9259-e314b366d011.png)

You can think of LCH as a cylindrical implementation of LAB, but one that is based more so on human perception.  In addition, the Luminance, Chroma, and Hue attributes do not affect one another.  

I don’t know if it’s possible, but I’d love to see it implemented as well :) Please see this [page](http://davidjohnstone.net/pages/lch-lab-colour-gradient-picker) for more details

![image](https://user-images.githubusercontent.com/20903247/30519110-1cb36ad0-9b5c-11e7-80a4-d37140cfb3f6.png)

**Comment by petterheterjag** [comment]
@jlarmstrongiv Thanks for bringing it up! I'm working on new version of the plugin where switching between color modes will be possible. Will probably get released within a few weeks :)

**Comment by petterheterjag** [comment]
@jlarmstrongiv Fixed with #6. Thanks for the feedback!

**Comment by jlarmstrongiv** [comment]
Wow, the update is awesome :) Thank you!!
