### ISSUE TITLE
Woking with rgba colors

### ISSUE THREAD

**Issue by hellofedorov** [petterheterjag/chromatic-sketch#5]
Hello! it can be cool if the plugin will able to make a gradient from one RGBA color to another. Thanks!
Now I need to use a fixed gradient from black-to-white such as a mask.

**Comment by petterheterjag** [comment]
@hellofedorov Ah, I see. I'll look into how hard it would be to make RGBA colors work.

**Comment by hellofedorov** [comment]
@petterheterjag thank you!

**Comment by petterheterjag** [comment]
@hellofedorov Fixed with #6. Thanks for the feedback!
